name: Auto update cleaned data

on:
  schedule:
    - cron: "0 6 1,15 * *"   # 1st & 15 each month at 06:00 UTC
  workflow_dispatch:          # to run manually in case

jobs:
  run-cleaning-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip

      - name: Run cleaning script
        run: |
          python clean_import.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data_processed/df_clean.csv
          git commit -m "Auto-update df_clean.csv via GitHub Actions" || echo "No changes to commit"
          git push